# Generated by Django 3.2.4 on 2021-06-23 10:04

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='missedingredients',
            name='image',
            field=models.TextField(default=datetime.datetime(2021, 6, 23, 10, 4, 46, 366915, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
